# Generated by Django 5.0.1 on 2026-04-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="plan",
            field=models.CharField(
                choices=[
                    ("STARTER", "Starter (Free)"),
                    ("GROWTH", "Growth"),
                    ("ENTERPRISE", "Enterprise"),
                ],
                default="STARTER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("TRIAL", "Trial"),
                    ("ACTIVE", "Active"),
                    ("PAST_DUE", "Past Due"),
                    ("CANCELED", "Canceled"),
                ],
                default="TRIAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
