# Generated by Django 5.0.1 on 2026-04-18 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_workspace_plan_workspace_subscription_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="plan_started_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
