# Generated by Django 5.0.1 on 2026-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequisition",
            name="category",
            field=models.CharField(
                choices=[
                    ("ENGINEERING", "Engineering"),
                    ("DESIGN", "Design"),
                    ("MARKETING", "Marketing"),
                    ("SALES", "Sales"),
                    ("OPERATIONS", "Operations"),
                    ("PRODUCT", "Product"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
