# Generated by Django 5.1.4 on 2026-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobanalysistask'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequisition',
            name='ai_condensed_requirements',
            field=models.TextField(blank=True, help_text='AI-generated summary of core requirements to save LLM tokens', null=True),
        ),
    ]
