# Generated by Django 6.0.4 on 2026-04-17 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="users.workspace",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="candidates.candidate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("candidate", "job")},
        ),
    ]
