# Generated by Django 5.0.1 on 2026-04-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="summary",
            field=models.TextField(
                blank=True, help_text="AI-generated candidate summary.", null=True
            ),
        ),
    ]
