# Generated by Django 5.0.1 on 2026-04-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_candidate_resume_candidate_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="category",
            field=models.CharField(
                choices=[
                    ("ENGINEERING", "Engineering"),
                    ("DESIGN", "Design"),
                    ("MARKETING", "Marketing"),
                    ("SALES", "Sales"),
                    ("OPERATIONS", "Operations"),
                    ("PRODUCT", "Product"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DRAFT", "Draft"),
                    ("EXPIRED", "Expired"),
                ],
                default="ACTIVE",
                max_length=15,
            ),
        ),
    ]
