# Generated by Django 5.0.1 on 2026-04-18 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0004_candidate_resume_candidate_summary"),
        ("users", "0003_workspace_plan_started_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Technical Round with CTO", max_length=255
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("SCREENING", "Initial Screening"),
                            ("TECHNICAL", "Technical Interview"),
                            ("CULTURAL", "Cultural Fit"),
                            ("FINAL", "Final Round"),
                        ],
                        default="TECHNICAL",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "location_link",
                    models.URLField(
                        blank=True,
                        help_text="Virtual meeting URL (Zoom, Meet, etc.)",
                        null=True,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="candidates.application",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="users.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
